spring:
  profiles:
    active: dev
    group:
      dev:
        - dev
      prod:
        - prod

# 개발용
---
# MYSQL 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database: mysql
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: ${AWS_S3_BUCKET}

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: ERROR

# 배포용
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database: mysql
    generate-ddl: true